steps:
  - name: $_BUILDER_IMAGE
    args:
      - --destination=public
  - name: $_BUILDER_IMAGE
    args:
      - deploy
      - --target=storage_bucket
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _BUILDER_IMAGE: 'ghcr.io/gohugoio/hugo:latest'