baseURL = "https://wasd.drewbrown.me"
title = "Drew's Tech Blog"
languageCode = 'en-us'

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
[params]
  author = "Drew Brown"
  description = "Drew's thoughts on coding for the cloud"
  menu_item_separator = " - "
  avatar = "images/drewbr.png"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/arbrown"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/drew_wasd"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/drew-brown-"
  # Orange theme (created by Gemini :D)
  [params.style]
    darkestColor = "#613600"  # Dark Orange (almost brown)
    darkColor = "#382100"     # Slightly lighter, still dark
    lightColor = "#f2d9b2"     # Very light orange (muted)
    lightestColor = "#f9e6d2"   # Even lighter for contrast
    primaryColor = "#e67700"   # Bright orange accent 

[module]
  [[module.imports]]
    path = "github.com/vaga/hugo-theme-m10c"

[deployment]
  [[deployment.targets]]
    name = "storage_bucket"
    URL = "gs://wasd-blog"

[markup]
  [markup.highlight]
    style = "monokai"
