baseURL = "https://wasd.drewbrown.me"
title = "Drew's Tech Blog"
locale = 'en-us'

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  author = "Drew Brown"
  description = "Drew's thoughts on coding for the cloud"
  menu_item_separator = " - "
  avatar = "images/drewbr.png"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/arbrown"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/drew_wasd"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/drew-brown-"

  # Orange theme colors
  [params.style]
    darkestColor = "#613600"  # Dark Orange (sidebar/header background)
    darkColor = "#382100"     # Main background
    lightColor = "#f2d9b2"    # Body text
    lightestColor = "#f9e6d2"  # Headings & highlights
    primaryColor = "#e67700"  # Bright orange accent

[deployment]
  [[deployment.targets]]
    name = "storage_bucket"
    URL = "gs://wasd-blog"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = false
